export const contactConstants = {
    REQUEST: 'CONTACTS_REQUEST',
    SUCCESS: 'CONTACTS_SUCCESS',
    FAILURE: 'CONTACTS_FAILURE',
    FILTERED: 'CONTACTS_FILTERED',
    FILTER_CLEANED: 'CONTACTS_FILTER_CLEANED',
    FILTER_CHANGED: 'CONTACTS_FILTER_CHANGED',
}

export const themeConstants = {CHANGE_THEME: "CHANGE_THEME"}