export const contactConstants = {
    REQUEST: 'CONTACTS_REQUEST',
    SUCCESS: 'CONTACTS_SUCCESS',
    FAILURE: 'CONTACTS_FAILURE',
    FILTERED: 'CONTACTS_FILTERED',
    FILTER_CLEANED: 'CONTACTS_FILTER_CLEANED'
}